### PR TITLE
Gives more code flexibility

### PR DESCRIPTION
**Pull request by ghost**
This work is based on the community feedbacks and the preliminaries modifications make by community contributors.
We suggest some modification to increase the code flexibility. 

- Peripherals init struct moved to variant folder
- Peripherals interrupt handlers moved to variant folder
- Init structures optimized to decrease RAM usage (~13% ram saving on BareMinimum)
- Some recurrent warnings removed

Only the stm32f1 library has been modified for the moment.

We wait community feedbacks before to merge with master branch.

### CODE REVIEW

**Comment by ghost** [comment]
More details:
- the support of other variant is easier #1 
- system clock configured to the maximum for nucleo #10 
- number of analog channel can be configured for each variant #25 
- decrease ram usage #27 but more work is required to optim
- proposed solution for #35

**Comment by danieleff** [comment]
1. The optimizations are good.
2. The move of structs to variants are good, however without the .*_alternate fully working its half the battle
3. I would not put the clock setup in variants, but leave inside core as:
```
#ifdef I2C1
if(... == I2C1) __HAL_RCC_I2C1_CLK_ENABLE();
#endif
```
4. I belive EXTI is the same on all chips / all series, so GPIO_EXTI_PARAM can remain in interrupt.c
5. variant_it.h file is not needed, could be deleted
6. I would not move NMI_Handler/HardFault_Handler/MemManage_Handler/BusFault_Handler/UsageFault_Handler/DebugMon_Handler/Error_Handler/SysTick_Handler into variant, unless there is an actual use case

**Comment by ghost** [comment]
Thank @danieleff for your feedback.

1. I think there are optimizations that can be performed inside Arduino function in core folder
2. Fully implemented when required (NoRemap, PartialRemap, FullRemap)
3. Clock settings has been moved inside core
4. You are right. All has been moved inside core
5. Files deleted
6. Processor interrupt handler has been moved to core folder. It was just to have a single file with all interrupt handler.

**Comment by fpistm** [comment]
Hi,
After discussion with fpr, we will rework F1 core based on the latest F4 core delivered (with mbed pinmap feature).

**Pull request closed without merging**
