### PR TITLE
Bmrework wip

### PR DESCRIPTION
**Pull request by fpistm**
Hi,
Same rework for boardManager for wip branch.
BR

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
This PR seems to be out of date.

As it looks like, its Pulling some of the changes from the WIP branch but not all of them.

I think it would be easier for me just to merge the WIP branch into the Master

**Comment by fpistm** [comment]
Hi,
in fact, I provided patch for the wip branch.
Goal was not to  merge the wip into master, only have the rework (boards.txt and platform.txt) for wip branch.
But feels free to merge wip into master.

**Comment by rogerclarkmelbourne** [comment]
Hi Frederic

OK. I will think I will merge WIP with Master , tomorrow (as its too late to do it today)

**Comment by fpistm** [comment]
No more needed on wip branch as merged to master.

**Pull request closed without merging**
