### PR TITLE
Rearrange Nucleo pin enums so that g_APinDescription index = pin name

### PR DESCRIPTION
**Pull request by danieleff**
Arduino numbers can still be used to access pins on Nucleo. Arduino 0 = PA3, Arduino 1 = PA2 ...

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Daniel, is that enum the right way around ?
e.g.

`PA3  = ARDUINO_PIN_D0,`

Shouldnt it be 

`ARDUINO_PIN_D0 = PA3`

**Comment by rogerclarkmelbourne** [comment]
Actually. So we need the ArduinoID field at all (in the long term)

Or perhaps do one step at a time and make sure it works

**Comment by danieleff** [comment]
Here is an other version: https://github.com/danieleff/Arduino_Core_STM32F1/commits/nucleo_pins_v2
It has 3 commits instead of 1 to be more clear.
I removed the `PA3 = ARDUINO_PIN_D0`. It is not necessary, it was meant to be a reminder that the order of the first 22 pins is significant, and matches the nucleo-arduino numbers.

**Comment by rogerclarkmelbourne** [comment]
I'll pulled this change to the WIP branch

Edit.

Tested using

ARDUINO_PIN_D13 on the Nucleo and just using 13, and it worked fine  (using the blink sketch to test)

**Comment by rogerclarkmelbourne** [comment]
I've pulled this to the WIP branch

**Pull request closed without merging**
