### PR TITLE
Simplify I2C code

### PR DESCRIPTION
**Pull request by danieleff**
I would like this reviewed, but basically replaces lots of stuff with two digital_io_init()s that already do the same.
Plus some unused field removal.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Seems to make sense, but I'd need to wire something up to confirm the code still runs.

BTW. Don't we still have an issue where the I2C pins are hard coded to only use the pins that the Nucleo uses.? (and these pins are the Alt function)
I recall looking at the issue a while ago, but the code needed loads of changes, and I didnt have time to even start it.

**Comment by danieleff** [comment]
For the I2C pins for different variants, the least intrusive way is to `#define I2C1_SDA_PIN GPIO_PIN_7` inside the variant.h, and use that in twi.c as: `.sda_pin = I2C1_SDA_PIN` 
(and same for .i2c_alternate, .sda_port, .scl_port, .scl_pin). 

The other end of the spectrum is to duplicate the whole structs in variants many times. I experimented with it, and actually did not like.

There may be possibilities in between, like use the default (the default pins are the same in all the chips (I think?)), and only change that in variants that do not want the default.

**Comment by ghost** [comment]
Thank you danielleff for your work.

> The other end of the spectrum is to duplicate the whole structs in variants many times. I experimented with it, and actually did not like.
There may be possibilities in between, like use the default (the default pins are the same in all the chips (I think?)), and only change that in variants that do not want the default.

We are also looking for a solution to move part of init structures in variant.cpp. 
We are in favor of all proposals.

**Comment by danieleff** [comment]
@fprwi6labs I wrote an answer into #35 about that issue.

**Pull request closed without merging**
