### PR TITLE
Fixed issues #18 and #19

### PR DESCRIPTION
**Pull request by ghost**
Wire library: replace twi.h to variant.h in wire header (more generic). #18 

Makefile: fix error (wrong name) and update with the possibility to compile only one lib. #19

### CODE REVIEW

**Comment by LMESTM** [comment]
There are conflicts with latest master so maybe you haven't created the patch against the latest commit or maybe this simply needs to be rebased as there have been changes since your post.  

For info, better to split this kind of PR into 2 separate PR, one for each Issue, I could have reviewed/merged the 1st one and investigate the 2nd one later

**Comment by rogerclarkmelbourne** [comment]
I have committed a fix for #18 

Re: #19 

The change won't auto merge.

because...
"This branch is 2 commits ahead, 2 commits behind stm32duino:master. "

I'll see if I can manually merge, as I agree with the change. In fact when I was testing the F100 build, I did something very similar by adding STM32F100 section to the makefile, but I deleted it before committing back to github

**Comment by rogerclarkmelbourne** [comment]
Thanks

I've manually merged your makefile, because your file was 2 commits behind the master.

BTW. I see I had made one mistake where I had not changed a dash "-" to underscore in the clean section.
So I've used your file, I just manually applied the changes for the commit which your repo was missing.

**Comment by LMESTM** [comment]
Excellent - thanks Roger !

**Comment by ghost** [comment]
Thank you Roger. 
Sorry for the problem with my commit. I will clone again the project to restart with a good version.

**Comment by rogerclarkmelbourne** [comment]
No worries

**Pull request closed without merging**
